AncientPoetry.Web/Controllers/FamoutPhraseController.cs
using AncientPoetry.Entities;
using AncientPoetry.IRepository.BaseFiles;
using Microsoft.AspNetCore.Mvc;

namespace AncientPoetry.Web.Controllers
{
    /// <summary>
    /// 名句控制器
    /// </summary>
    public class FamoutPhraseController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public FamoutPhraseController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public IActionResult Index()
        {
            var famousPhrase = _unitOfWork.FamoutPhrase.GetAll();
            return View(famousPhrase);
        }

        #region 创建

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(FamoutPhrase famoutPhrase)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.FamoutPhrase.Add(famoutPhrase);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        #endregion

        #region 编辑

        public IActionResult Edit(int famoutPhraseId)
        {
            FamoutPhrase? famoutPhrase = _unitOfWork.FamoutPhrase.Get(u => u.Id == famoutPhraseId);
            if (famoutPhrase == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(famoutPhrase);
        }

        [HttpPost]
        public IActionResult Edit(FamoutPhrase famoutPhrase)
        {
            if (ModelState.IsValid && famoutPhrase.Id > 0)
            {
                _unitOfWork.FamoutPhrase.Update(famoutPhrase);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        #endregion

        #region 删除

        public IActionResult Delete(int famoutPhraseId)
        {
            FamoutPhrase? famoutPhrase = _unitOfWork.FamoutPhrase.Get(u => u.Id == famoutPhraseId);
            if (famoutPhrase == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(famoutPhrase);
        }

        [HttpPost]
        public IActionResult Delete(FamoutPhrase famoutPhrase)
        {
            FamoutPhrase? objFromDb = _unitOfWork.FamoutPhrase.Get(u => u.Id == famoutPhrase.Id);
            if (objFromDb is not null)
            {
                _unitOfWork.FamoutPhrase.Remove(objFromDb);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        #endregion

    }
}

AncientPoetry.Web/Views/FamoutPhrase/Create.cshtml
@model FamoutPhrase

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create FamoutPhrase</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly"></div> *@
                <div class="form-floating py-2 col-12">
                    <textarea asp-for="Content" class="ms-2"></textarea>
                    <label asp-for="Content" class="ms-2"></label>
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Source" class="form-control border shadow" />
                    <label asp-for="Source" class="ms-2"></label>
                    <span asp-validation-for="Source" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Author" class="form-control border shadow" />
                    <label asp-for="Author" class="ms-2"></label>
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DynastyName" class="form-control border shadow" />
                    <label asp-for="DynastyName" class="ms-2"></label>
                    <span asp-validation-for="DynastyName" class="text-danger"></span>
                </div>
                


                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="FamoutPhrase" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons  lists   table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough |  align lineheight | numlist bullist indent outdent',
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AncientPoetry.Web/Views/FamoutPhrase/Delete.cshtml
@model FamoutPhrase

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create FamoutPhrase</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly"></div> *@
                <div class="form-floating py-2 col-12">
                    <textarea asp-for="Content" class="ms-2" disabled></textarea>                    
                    <label asp-for="Content" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Source" class="form-control border shadow" disabled />
                    <label asp-for="Source" class="ms-2"></label>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Author" class="form-control border shadow" disabled />
                    <label asp-for="Author" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DynastyName" class="form-control border shadow"  disabled/>
                    <label asp-for="DynastyName" class="ms-2"></label>                    
                </div>


                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <i class="bi bi-check-circle"></i> Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="FamoutPhrase" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons  lists   table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough |  align lineheight | numlist bullist indent outdent',
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AncientPoetry.Web/Views/FamoutPhrase/Edit.cshtml
@model FamoutPhrase

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create FamoutPhrase</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly"></div> *@
                <div class="form-floating py-2 col-12">
                    <textarea asp-for="Content" class="ms-2"></textarea>
                    <label asp-for="Content" class="ms-2"></label>
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">                    
                    <input asp-for="Source" class="form-control border shadow" />
                    <label asp-for="Source" class="ms-2"></label>
                    <span asp-validation-for="Source" class="text-danger"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="Author" class="form-control border shadow" />
                    <label asp-for="Author" class="ms-2"></label>
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DynastyName" class="form-control border shadow" />
                    <label asp-for="DynastyName" class="ms-2"></label>
                    <span asp-validation-for="DynastyName" class="text-danger"></span>
                </div>



                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Edit
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="FamoutPhrase" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons  lists   table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough |  align lineheight | numlist bullist indent outdent',
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AncientPoetry.Web/Views/FamoutPhrase/Index.cshtml
@model IEnumerable<FamoutPhrase>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">名句 List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="FamoutPhrase" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create New FamoutPhrase
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Content</th>
                    <th>Source</th>
                    <th>Author</th>
                    <th>DynastyName</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@Html.Raw(obj.Content)</td>
                        <th>@obj.Source</th>
                        <td>@obj.Author</td>
                        <td>@obj.DynastyName</td>
                        <td>
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="FamoutPhrase" asp-action="Edit" asp-route-famoutPhraseId="@obj.Id" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="FamoutPhrase" asp-action="Delete" asp-route-famoutPhraseId="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>