AncientPoetry.Web/Controllers/DynastyController.cs
using AncientPoetry.Entities;
using AncientPoetry.IRepository.BaseFiles;
using Microsoft.AspNetCore.Mvc;

namespace AncientPoetry.Web.Controllers
{
    /// <summary>
    /// 朝代
    /// </summary>
    public class DynastyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DynastyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public IActionResult Index()
        {
            var dynasties = _unitOfWork.Dynasty.GetAll();
            return View(dynasties);
        }

        #region 创建

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Dynasty dynasty)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Dynasty.Add(dynasty);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        #endregion

        #region 更新

        public IActionResult Update(int dynastyId)
        {
            Dynasty? dynasty = _unitOfWork.Dynasty.Get(u => u.Id == dynastyId);
            if (dynasty == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(dynasty);
        }

        [HttpPost]
        public IActionResult Update(Dynasty dynasty)
        {
            if (ModelState.IsValid && dynasty.Id > 0)
            {
                _unitOfWork.Dynasty.Update(dynasty);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        #endregion

        #region 删除

        public IActionResult Delete(int dynastyId)
        {
            Dynasty? dynasty = _unitOfWork.Dynasty.Get(u => u.Id == dynastyId);
            if (dynasty == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(dynasty);
        }

        [HttpPost]
        public IActionResult Delete(Dynasty dynasty)
        {
            Dynasty? objFromDb = _unitOfWork.Dynasty.Get(u => u.Id == dynasty.Id);
            if (objFromDb is not null)
            {
                _unitOfWork.Dynasty.Remove(objFromDb);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        #endregion

    }
}

AncientPoetry.Web/Controllers/PoemController.cs
using AncientPoetry.Entities;
using AncientPoetry.IRepository.BaseFiles;
using Microsoft.AspNetCore.Mvc;

namespace AncientPoetry.Web.Controllers
{
    /// <summary>
    /// 诗歌控制器
    /// </summary>
    public class PoemController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PoemController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var poem = _unitOfWork.Poem.GetAll();
            return View(poem);
        }

        #region 创建

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Poem poem)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Poem.Add(poem);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        #endregion

        #region 编辑

        public IActionResult Edit(int poemId)
        {
            Poem? poem = _unitOfWork.Poem.Get(u => u.Id == poemId);
            if (poem == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(poem);
        }

        [HttpPost]
        public IActionResult Edit(Poem poem)
        {
            if (ModelState.IsValid && poem.Id > 0)
            {
                _unitOfWork.Poem.Update(poem);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        #endregion

        #region 删除

        public IActionResult Delete(int poemId)
        {
            Poem? poem = _unitOfWork.Poem.Get(u => u.Id == poemId);
            if (poem == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(poem);
        }

        [HttpPost]
        public IActionResult Delete(Poem poem)
        {
            Poem? objFromDb = _unitOfWork.Poem.Get(u => u.Id == poem.Id);
            if (objFromDb is not null)
            {
                _unitOfWork.Poem.Remove(objFromDb);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        #endregion


    }
}

AncientPoetry.Web/Controllers/PoetController.cs
using AncientPoetry.IRepository.BaseFiles;
using Microsoft.AspNetCore.Mvc;

namespace AncientPoetry.Web.Controllers
{
    /// <summary>
    /// 诗人控制器
    /// </summary>
    public class PoetController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PoetController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }



        public IActionResult Index()
        {
            var poets = _unitOfWork.Poet.GetAll();
            return View(poets);
        }



    }
}

AncientPoetry.Web/Controllers/ProblemController.cs
using AncientPoetry.IRepository.BaseFiles;
using Microsoft.AspNetCore.Mvc;

namespace AncientPoetry.Web.Controllers
{
    /// <summary>
    /// 问题控制器
    /// </summary>
    public class ProblemController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ProblemController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public IActionResult Index()
        {
            var problem = _unitOfWork.Problem.GetAll();
            return View(problem);
        }


        #region 创建

        public IActionResult Create()
        {
            return View();
        }

        #endregion


        #region 编辑

        public IActionResult Edit()
        {
            return View();
        }

        #endregion


        #region 删除

        public IActionResult Delete()
        {
            return View();
        }

        #endregion


    }
}

AncientPoetry.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AncientPoetry.Web</title>
    @* 深色主题的链接 *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />



    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AncientPoetry.Web.styles.css" asp-append-version="true" />


    @* 图标的链接 *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    @* 提示信息的CSS链接 *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/spinner.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AncientPoetry.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Dynasty" asp-action="Index">Dynasty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Poet" asp-action="Index">Poet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Poem" asp-action="Index">Poem</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="FamoutPhrase" asp-action="Index">FamoutPhrase</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="ProblemType" asp-action="Index">ProblemType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Problem" asp-action="Index">Problem</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AncientPoetry.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @* Rich Text Editor *@
    <script src="https://cdn.tiny.cloud/1/g28lhnxtlihu4l4a381gw7tz47voznshwbi10lmsvlekrfme/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>